version: "3"
services:
  bort-backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "5005:5005"
    networks:
      bort:
    env_file:
      - ./backend/.env

  bort-frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      bort:

networks:
  bort:
